apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: granite3b
  namespace: model-deploy-lab
  annotations:
    openshift.io/display-name: "Granite 3.3 2B Instruct"
    security.opendatahub.io/enable-auth: "true"
    opendatahub.io/hardware-profile-name: gpu-profile
    opendatahub.io/hardware-profile-namespace: redhat-ods-applications
    serving.kserve.io/deploymentMode: RawDeployment
    serving.kserve.io/runtime: vllm-cuda-runtime
  labels:
    networking.kserve.io/visibility: exposed
    opendatahub.io/dashboard: "true"
spec:
  predictor:
    serviceAccountName: granite-sa
    model:
      modelFormat:
        name: vLLM
      runtime: vllm-cuda-runtime
      
      # --- FIX: USE STANDARD URI SYNTAX ---
      # This bypasses the "storage-config" webhook error.
      # Format: s3://<bucket_name>/<folder_name>
      storageUri: s3://models/granite3b
      
      resources:
        requests:
          cpu: "4"
          memory: "16Gi"
          nvidia.com/gpu: "1"
        limits:
          cpu: "8"
          memory: "24Gi"
          nvidia.com/gpu: "1"
      
      args:
        - "--model"
        - "/mnt/models" 
        - "--port"
        - "8080"
        - "--max-model-len"
        - "8192"
        - "--gpu-memory-utilization"
        - "0.9"
        - "--distributed-executor-backend"
        - "mp"